### PR TITLE
Avoid requiring user's server to be Clone

### PR DESCRIPTION
**Pull request by jonhoo**
The old code took a bit of a shortcut, cloning the user's `Server` type for every request. This was hidden behind `tokio_proto::NewService`, but if you look at it, all it does is clone its argument whenever `new_service()` is invoked. This is inconvenient for users, as it means they need to carefully craft their `Server` type such that it is in fact `Clone`. This will likely involve adding reference counts to all fields, or create an `Arc` wrapper, implement `Service` for it, and then using that to call `.listen()`.

This commit essentially does this for the user. The `Server` given by the user is wrapped in an `Arc` that implements `Service` if the contained value does. When a new request arrives, only this `Arc` is cloned, not the underlying `Server`. Since all the methods on `Service` take & receivers, this works fine. It should also lead to a decent performance improvement as we do potentially much less work for every incoming request.

In terms of API changes, this relaxes the requirements on the user's `Server` type from

```
Send + 'static + Clone (which adds + Sized)
```

to

```
Send + 'static + Sync + Sized
```

which should be backwards compatible for all but the weirdest types (i.e., something which implements `Clone` but not `Sync`). If we want to support those too, this is doable, but we should put off that added complexity until we have a use-case for it.

### CODE REVIEW

**Comment by tikue** [comment]
Thanks for the PR! I'm borderline on this; we used to actually do this and just require `Sync` + `Send`, but I changed it to reflect the fact that `NewService` basically only requires `Clone`. It seems to me that there's potentially more overhead involved with this change; namely, the user no longer has the choice to impl `Clone` in a way that's cheaper than an atomic operation.

**Comment by jonhoo** [comment]
`NewService` requires `Clone + Send`, no? So the question is whether to require `Sync` and do (atomic) reference counting for the user, or to require `Clone` and make the user implement the cloning strategy they see fit. One can make an argument either way, but given `tarpc`'s focus on being "an RPC framework for rust with a focus on **ease of use**", I'd say `Sync` is an easier requirement to get your head around. It's non-trivial to correctly write the `Arc` wrapper for your own type such that it still implements `Service` as required. `Sync`, in most cases, requires no special consideration on the part of the user.

**Comment by jonhoo** [comment]
I also think that, in all but the most trivial servers, it will be cheaper to do atomic reference counting than a full struct `.clone()`. And I'm struggling to come up with examples of a complex server where the user could write a more intelligent `.clone()` implementation.

**Comment by tikue** [comment]
I do agree that `Sync` is easier pedagogically. It's also true that a core tenet of tarpc is being easy to understand and use. You mentioned only the weirdest types implement `Clone` but not `Sync`. I'd like to dispute this, because the original impetus to switch to `Clone` rather than `Sync` is because most `Sync` types are trivially `Clone` but the reverse is not true. For instance, if a service contains a `std::sync::mpsc::Sender`, the only way to make it `Sync` is to wrap it in a Mutex! This came up in examples I was writing, so it's not a rare occurrence as far as I can tell.

So that being said, I think this is very useful feedback, and it's probably worth opening an issue to keep this discussion going. One very important use case that remains to be determined is how tokio will create sharable clients. Currently they require wrapping in a Mutex, but if in the future the client works similarly to an mpsc channel and requires being cloned to share across threads, that'd be a major point in favor of the status quo. If they are `Sync`, that would greatly encourage us to switch. Of course, it's all just speculation at this point.

**Comment by jonhoo** [comment]
That's a good point. Though I think `std::sync::mpsc::Sender` is somewhat special in this regard. Here's my reasoning: in general, your server will either need to mutate state, or not mutate state, for any given incoming request. If it does not need to mutate state, `Sync` is obviously more efficient. If it _does_ need to mutate state, then with `Clone`, you'd need some kind of `Arc` so the different clones can refer to the same shared data. That `Arc` will then probably need to contain a `Mutex` or an `RwLock` to allow concurrent access. Moving `Arc` into `tarpc` and only requiring `Sync` removes one layer of complexity from the user's code, at no additional cost. `mpsc::Sender` is special in that it provides **mutable** access through a **read-only, non-`Sync` borrow**, **and** it allows clones to "access" the same **shared** channel. I know of very few other types that fit this description, yet they are (afaict) the only ones that do _not_ mash well with the proposed `Sync` setup.

Now, all that said, I completely agree that it's unfortunate for `mpsc::Sender` to be something that isn't efficiently supported. Implementers **can** get around this by having a wrapper like this for their channel:

``` rust
struct SyncSender<T>(mpsc::Sender<T>);
unsafe impl<T> Sync for SyncSender<T> {}
impl<T> SyncSender<T> {
  fn clone(&self) -> mpsc::Sender<T> {
    self.0.clone()
  }
}
```

Now they can stick that in their server, and when they need a channel, they clone it on demand. I'd argue this is much simpler than what we're requiring users to do to use `Arc`s when the requirement is `Sync`, but maybe that's a matter of personal preference.

It'd be really neat if there was a way to provide support for both `Clone` and `Sync` types separately, but I don't think Rust's type system is quite up to that task.

**Comment by tikue** [comment]
I do like the notion of providing support for both `Clone` and `Sync` style services, but I'd be wary of increasing the API surface, and I think trying to support both with a single trait would have trait impl coherence issues.

I'm going to close this but am definitely interested in keeping a conversation going about this trap/pitfall. At the very least, documentation of the current state of things would be helpful. https://github.com/google/tarpc/issues/64

**Pull request closed without merging**
